name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NETCORE_VERSION: 3.1.101

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Build
      run: dotnet build --configuration Release --output ./output
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: drop
        # A file, directory or wildcard pattern that describes what to upload
        path: ./output
