name: Deploy

on:
  push:
    branches: 
    - release

env:
  NETCORE_VERSION: 3.1.101

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core ${{ env.NETCORE_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.NETCORE_VERSION }}

    - name: Build
      run: dotnet build --configuration Release --output ./output
    
    - name: Azure Login
      uses: Azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.4
      with:
        # Name of the Azure Function App
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        # Path to package or folder. *.zip or a folder to deploy
        package: ./output
